[WIP] Basic IntelLibrary ActiveConfig working
But there are errors with the JSON Newtonsoft conversion of the internal objects:

InvalidOperationException: No coercion operator is defined between types 'IGCLWrapper.ctl_lace_lux_aggr_map_entry_t*' and 'System.Object'.